[mypy]
strict = true
exclude = (tests/|\.git|\.venv|local)
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
ignore_missing_imports = false
warn_unused_configs = true
warn_unreachable = true
show_error_codes = true
disallow_any_generics = false
disallow_untyped_defs = false
implicit_reexport = false
disallow_untyped_decorators = false
warn_return_any = true